services:
  app:
    image: plexinc/pms-docker:latest
    environment:
      - TZ=America/Chicago
      - PLEX_UID=998
      - PLEX_GID=998
    networks:
      - outside
    volumes:
      - plex-config:/config
      - mnt-public:/mnt/RAID/public
      - mnt-tyler:/mnt/RAID/tyler

networks:
  outside:
    external: true
    name: host

volumes:
  plex-config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fileserver.localdomain.lan,rw,vers=4.1
      device: ":/srv/docker/plex"
  mnt-public:
    external: true
  mnt-tyler:
    external: true

