services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
      - PLEX_UID=998
      - PLEX_GID=998
    network_mode: host
    volumes:
      - plex-config:/config
      - mnt-public:/mnt/RAID/public
      - mnt-tyler:/mnt/RAID/tyler


volumes:
  plex-config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fileserver.localdomain.lan,rw,vers=4.1
      device: ":/srv/docker/plex"
  mnt-public:
  mnt-tyler:

