services:
  plex:
    container_name: plex
    restart: unless-stopped
    image: plexinc/pms-docker:latest
    environment:
      - TZ=America/Chicago
      - PLEX_UID=1000
      - PLEX_GID=1000
    network_mode: host 
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - 105
    volumes:
      - ./DBRepair.sh:/DBRepair.sh
      - ./config:/config
      #- /mnt/public:/mnt/RAID/public
      #- /mnt/tyler:/mnt/RAID/tyler
      - mnt-public:/mnt/RAID/public
      - mnt-tyler:/mnt/RAID/tyler
      - ./transcode:/transcode
      #- /dev/shm:/transcode
      #- /dev/dri:/dev/dri

  tautulli:
    container_name: tautulli
    restart: unless-stopped
    image: ghcr.io/tautulli/tautulli
    volumes:
      - ./config-tautulli:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - 8181:8181

  pasta:
    image: cglatot/pasta
    container_name: pasta
    ports:
      - 8087:80
    restart: unless-stopped


volumes:
  #backup:
  #  driver: local
  #  driver_opts:
  #    type: nfs
  #    o: addr=fileserver.tyler-clark.com,rw,vers=4.1
  #    device: ":/mnt/docker/plex-docker/config"
  mnt-public:
    external: true
  mnt-tyler:
    external: true

