services:
  plex:
    restart: unless-stopped
    image: plexinc/pms-docker:latest
    environment:
      - TZ=America/Chicago
      - PLEX_UID=1000
      - PLEX_GID=1000
    network_mode: host 
    volumes:
      - ./DBRepair.sh:/DBRepair.sh
      - ./config:/config
      - mnt-public:/mnt/RAID/public
      - mnt-tyler:/mnt/RAID/tyler
      - ./transcode:/transcode
      - /dev/dri:/dev/dri
  pasta:
    image: cglatot/pasta
    container_name: pasta
    ports:
      - 8087:80
    restart: unless-stopped


volumes:
  #backup:
  #  driver: local
  #  driver_opts:
  #    type: nfs
  #    o: addr=fileserver.tyler-clark.com,rw,vers=4.1
  #    device: ":/mnt/docker/plex-docker/config"
  mnt-public:
    external: true
  mnt-tyler:
    external: true

